; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32@6.13.0
framework = espidf
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep
lib_compat_mode = off
extra_scripts = pre:generate_version.py

platform_packages =
	platformio/framework-espidf @ 3.50503.0

lib_deps = 
	symlink://../esp32-utilities
	fastled/FastLED@3.10.3
	mikalhart/TinyGPSPlus@^1.0.3
	adafruit/Adafruit HMC5883 Unified@^1.2.1
	adafruit/Adafruit GFX Library@^1.11.5
	adafruit/Adafruit Unified Sensor@^1.1.9
	adafruit/Adafruit BusIO@^1.14.1
	bblanchon/ArduinoJson@^7.0.0
	madhephaestus/ESP32Encoder@^0.12.0
	bblanchon/StreamUtils@^1.7.3
	https://github.com/Blake-Ballew/Adafruit_LIS2MDL.git
	https://github.com/Blake-Ballew/Adafruit_LSM303_Accel.git
	https://github.com/Blake-Ballew/arduino-LoRa.git
board_build.partitions = partition_table_v2_plus.csv
board_upload.flash_size = 16MB
build_flags =
	-std=gnu++17
	-Iinclude/HelperClasses/LoRaDriver/*
	-Iinclude/HelperClasses/Window/*
	-Iinclude/HelperClasses/Window/States/*
build_unflags = 
	-std=gnu++11
	-Werror=all
; Needed to build using esp-idf with Arduino component:
; https://community.platformio.org/t/framework-espidf-fails-to-build-by-giving-no-error-notice/44442/6
board_build.embed_txtfiles =
    managed_components/espressif__esp_insights/server_certs/https_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt
	
[env:local-library-v1]
board = esp32dev
board_build.f_flash = 80000000L
board_build.partitions = partition_table.csv
board_upload.flash_size = 4MB
build_flags = 
	${env.build_flags}
	-D DUSE_FAKE_GPS_COORDS=0
	-D HARDWARE_VERSION=1
	"-I../esp32-utilities/*"
lib_deps = 
	${env.lib_deps}
	adafruit/Adafruit SSD1306@^2.5.7

[env:local-library-v2]
board = esp32dev
board_build.f_flash = 80000000L
board_build.flash_mode = dio
build_flags = 
	${env.build_flags}
	-D DUSE_FAKE_GPS_COORDS=0
	-D HARDWARE_VERSION=2
	"-I../esp32-utilities/*"
lib_deps = 
	${env.lib_deps}
	adafruit/Adafruit SSD1306@^2.5.7

[env:hardware-v3]
board = esp32-s3-devkitm-1

build_flags =
	${env.build_flags}
	-D DUSE_FAKE_GPS_COORDS=0
	-D HARDWARE_VERSION=3
	-D USE_V3_OLED
	"-I../esp32-utilities/*"
	-D ARDUINO_USB_CDC_ON_BOOT=1 
lib_deps = 
	${env.lib_deps}
	piotrmalek/BQ25672@^0.1.1
	adafruit/Adafruit SH110X@^2.1.14
	adafruit/Adafruit MMC56x3@1.0.2
	https://github.com/DFRobot/DFRobot_BMM350.git
	7semi-solutions/7Semi BMI323@^1.0.0
	https://github.com/Blake-Ballew/Adafruit_LSM6DS.git

[env:hardware-v3-tag-connect]
board = esp32-s3-devkitm-1

build_flags =
	${env.build_flags}
	-D DUSE_FAKE_GPS_COORDS=0
	-D HARDWARE_VERSION=3
	-D USE_V3_OLED
	"-I../esp32-utilities/*"
lib_deps = 
	${env.lib_deps}
	piotrmalek/BQ25672@^0.1.1
	adafruit/Adafruit SH110X@^2.1.14
	adafruit/Adafruit MMC56x3@1.0.2
	https://github.com/DFRobot/DFRobot_BMM350.git
	7semi-solutions/7Semi BMI323@^1.0.0
	https://github.com/Blake-Ballew/Adafruit_LSM6DS.git
